import glob
import json
from pathlib import Path

import pandas as pd

from mssim.config import PROJECT_ROOT


class MSSIMPlotParser:
    """Parser for MSSIM plotting data.

    This class provides methods to parse JSONL result files generated by MSSIM
    and convert them into pandas DataFrames suitable for plotting.
    """

    def __init__(self, settings_path) -> None:
        self.settings = self.load_json(settings_path)

    def load_json(self, filepath: str | Path) -> dict:
        """Load a JSON file and return its contents as a dictionary."""
        with open(filepath) as fh:
            return json.load(fh)

    def get_input_files(self) -> list[Path]:
        """Get all input files specified in the settings config. Resolves the input filename 
        using wildcard parsing (glob).
        """
        input_cfg = self.settings.get("input", {})
        rel_path = input_cfg.get("rel_path")
        filename = input_cfg.get("filename")

        input_dir = PROJECT_ROOT / rel_path

        input_dir.mkdir(parents=True, exist_ok=True)

        # Use glob to find all matching paths cleanly
        matched = glob.glob(str(input_dir / filename))

        return sorted([Path(p) for p in matched])

    def parse_file(self, filepath: str | Path) -> pd.DataFrame:
        """Parse JSONL result file(s)."""

        # Extract kwargs keys dynamically from config
        model_cfg = self.settings.get("model", {})
        kwargs = model_cfg.get("kwargs", {})
        kwargs_keys = list(kwargs.keys())

        rows = []
        with open(filepath) as fh:
            for line in fh:
                if not line.strip():
                    continue
                obj = json.loads(line)
                metadata = obj.get("metadata", {})

                # Recover kwargs values from metadata dynamically
                for key in kwargs_keys:
                    obj[key] = metadata.get(key)

                rows.append(obj)

        if not rows:
            return pd.DataFrame()

        df = pd.DataFrame(rows)
        drop = [
            "elapsed_seconds",
            "fidelity",
            "metadata",
            "timestamp",
            "parameters",
            "n_params",
        ]
        return df.drop(columns=[c for c in drop if c in df.columns])

    def parse(self, filepaths: list[str | Path] = None) -> pd.DataFrame:
        """Parse a list of file paths and return a concatenated pandas DataFrame."""
        dfs = []
        filepaths = filepaths or self.get_input_files()

        for filepath in filepaths:
            dfs.append(self.parse_file(filepath))

        if not dfs:
            return pd.DataFrame()

        return pd.concat(dfs, ignore_index=True)
